apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coe-spring-webpromote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coe-spring-webpromote
    spec:
      containers:
        - name: coe-spring-webpromote
          image: snyamars007/coe-spring-webpromote:latest
          ports:
            - containerPort: 8091
              protocol: HTTP
